# Generated by Django 4.2.30 on 2026-06-06 18:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "base_prompt",
                    models.TextField(
                        help_text="Instrucao generica enviada ao LLM (tema, formato yes/no, restricoes)."
                    ),
                ),
                (
                    "criteria",
                    models.TextField(
                        blank=True, help_text="Criterios de inclusao/exclusao (I/E)."
                    ),
                ),
                (
                    "prompt_structure",
                    models.CharField(
                        choices=[
                            ("V1", "V1 - single user message (Li 2024)"),
                            ("V2", "V2 - system + user (Dennstadt 2024)"),
                        ],
                        default="V2",
                        max_length=2,
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        choices=[
                            ("openai", "OpenAI GPT-4o (cloud)"),
                            ("deepseek", "DeepSeek-V4-Flash (cloud)"),
                            ("groq", "Groq Llama-3.3-70B (cloud)"),
                            ("ollama", "Ollama qwen3:8B (local)"),
                        ],
                        default="deepseek",
                        max_length=20,
                    ),
                ),
                (
                    "model",
                    models.CharField(
                        blank=True,
                        help_text="Vazio = default do provider.",
                        max_length=120,
                    ),
                ),
                ("temperature", models.FloatField(default=0.0)),
                ("max_tokens", models.IntegerField(default=100)),
                ("no_think", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={"ordering": ["-created_at"],},
        ),
        migrations.CreateModel(
            name="ScreeningRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        choices=[
                            ("openai", "OpenAI GPT-4o (cloud)"),
                            ("deepseek", "DeepSeek-V4-Flash (cloud)"),
                            ("groq", "Groq Llama-3.3-70B (cloud)"),
                            ("ollama", "Ollama qwen3:8B (local)"),
                        ],
                        max_length=20,
                    ),
                ),
                ("model", models.CharField(blank=True, max_length=120)),
                (
                    "prompt_structure",
                    models.CharField(
                        choices=[
                            ("V1", "V1 - single user message (Li 2024)"),
                            ("V2", "V2 - system + user (Dennstadt 2024)"),
                        ],
                        max_length=2,
                    ),
                ),
                ("temperature", models.FloatField(default=0.0)),
                ("max_tokens", models.IntegerField(default=100)),
                ("no_think", models.BooleanField(default=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Em fila"),
                            ("running", "A correr"),
                            ("done", "Concluido"),
                            ("error", "Erro"),
                            ("cancelled", "Cancelado"),
                        ],
                        default="pending",
                        max_length=12,
                    ),
                ),
                ("total", models.IntegerField(default=0)),
                ("processed", models.IntegerField(default=0)),
                ("tokens", models.IntegerField(default=0)),
                ("error", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="runs",
                        to="screening.project",
                    ),
                ),
            ],
            options={"ordering": ["-created_at"],},
        ),
        migrations.CreateModel(
            name="Record",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "idx",
                    models.IntegerField(help_text="Indice 0-based dentro do projeto."),
                ),
                ("title", models.TextField()),
                ("abstract", models.TextField(blank=True)),
                ("doi", models.CharField(blank=True, max_length=200)),
                ("pmid", models.CharField(blank=True, max_length=30)),
                ("journal", models.TextField(blank=True)),
                ("authors", models.TextField(blank=True)),
                ("publication_date", models.CharField(blank=True, max_length=40)),
                ("pubmed_url", models.URLField(blank=True)),
                (
                    "gold_label",
                    models.IntegerField(
                        blank=True, help_text="Gold standard opcional.", null=True
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="records",
                        to="screening.project",
                    ),
                ),
            ],
            options={"ordering": ["idx"], "unique_together": {("project", "idx")},},
        ),
        migrations.CreateModel(
            name="Prediction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "pred",
                    models.IntegerField(
                        default=-1, help_text="1 incluir, 0 excluir, -1 nao parseado."
                    ),
                ),
                ("per_criterion", models.JSONField(blank=True, default=list)),
                ("raw_response", models.TextField(blank=True)),
                (
                    "reviewer_decision",
                    models.IntegerField(
                        blank=True,
                        help_text="Override humano: 1 incluir, 0 excluir, null = nao revisto.",
                        null=True,
                    ),
                ),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "record",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="predictions",
                        to="screening.record",
                    ),
                ),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="predictions",
                        to="screening.screeningrun",
                    ),
                ),
            ],
            options={
                "ordering": ["record__idx"],
                "unique_together": {("run", "record")},
            },
        ),
    ]
